#ifndef _SCENE_H_
#define _SCENE_H_

#include <GL/gl.h>
#include <GL/glu.h>

#include "framework/scenemanager/scenemanager.h"

// arrays ocntaining pointers to root nodes of all scenes scenes
extern struct S_sceneNode *beginning[];
extern struct S_sceneNode *scene0[];
extern struct S_sceneNode *scene1[];
extern struct S_sceneNode *ending[];


enum E_BEGINNING{
        E_B_ROOT = 0,
        // piano
        E_B_PIANO_BODY,
        E_B_PIANO_BENCH,
        E_B_PIANO_STRINGS,
        // all keys
        E_B_PIANO_C0, E_B_PIANO_CC0, E_B_PIANO_D0, E_B_PIANO_DD0, E_B_PIANO_E0, E_B_PIANO_F0, E_B_PIANO_FF0, E_B_PIANO_G0, E_B_PIANO_GG0, E_B_PIANO_A0, E_B_PIANO_AA0, E_B_PIANO_B0,
        E_B_PIANO_C1, E_B_PIANO_CC1, E_B_PIANO_D1, E_B_PIANO_DD1, E_B_PIANO_E1, E_B_PIANO_F1, E_B_PIANO_FF1, E_B_PIANO_G1, E_B_PIANO_GG1, E_B_PIANO_A1, E_B_PIANO_AA1, E_B_PIANO_B1,
        E_B_PIANO_C2, E_B_PIANO_CC2, E_B_PIANO_D2, E_B_PIANO_DD2, E_B_PIANO_E2, E_B_PIANO_F2, E_B_PIANO_FF2, E_B_PIANO_G2, E_B_PIANO_GG2, E_B_PIANO_A2, E_B_PIANO_AA2, E_B_PIANO_B2,
        E_B_PIANO_C3, E_B_PIANO_CC3, E_B_PIANO_D3, E_B_PIANO_DD3, E_B_PIANO_E3, E_B_PIANO_F3, E_B_PIANO_FF3, E_B_PIANO_G3, E_B_PIANO_GG3, E_B_PIANO_A3, E_B_PIANO_AA3, E_B_PIANO_B3,
        E_B_PIANO_C4, E_B_PIANO_CC4, E_B_PIANO_D4, E_B_PIANO_DD4, E_B_PIANO_E4, E_B_PIANO_F4, E_B_PIANO_FF4, E_B_PIANO_G4, E_B_PIANO_GG4, E_B_PIANO_A4, E_B_PIANO_AA4, E_B_PIANO_B4,
        E_B_PIANO_C5, E_B_PIANO_CC5, E_B_PIANO_D5, E_B_PIANO_DD5, E_B_PIANO_E5, E_B_PIANO_F5, E_B_PIANO_FF5, E_B_PIANO_G5, E_B_PIANO_GG5, E_B_PIANO_A5, E_B_PIANO_AA5, E_B_PIANO_B5,
        E_B_PIANO_C6, E_B_PIANO_CC6, E_B_PIANO_D6, E_B_PIANO_DD6, E_B_PIANO_E6, E_B_PIANO_F6, E_B_PIANO_FF6, E_B_PIANO_G6, E_B_PIANO_GG6, E_B_PIANO_A6, E_B_PIANO_AA6, E_B_PIANO_B6,
        E_B_PIANO_C7, E_B_PIANO_CC7, E_B_PIANO_D7, E_B_PIANO_DD7, E_B_PIANO_E7, E_B_PIANO_F7, E_B_PIANO_FF7, E_B_PIANO_G7, E_B_PIANO_GG7, E_B_PIANO_A7, E_B_PIANO_AA7, E_B_PIANO_B7,
        E_B_PIANO_C8, E_B_PIANO_CC8, E_B_PIANO_D8, E_B_PIANO_DD8, E_B_PIANO_E8, E_B_PIANO_F8, E_B_PIANO_FF8, E_B_PIANO_G8, E_B_PIANO_GG8, E_B_PIANO_A8, E_B_PIANO_AA8, E_B_PIANO_B8,
        // ground
        E_B_GROUND,
        //texts
        E_B_NAME,
        E_B_NAME0, E_B_NAME1, E_B_NAME2, E_B_NAME3, E_B_NAME4, E_B_NAME5, E_B_NAME6, E_B_NAME7, E_B_NAME8, E_B_NAME9, E_B_NAME10, E_B_NAME11,

        E_B_SCHOOL,
        E_B_SCHOOL0, E_B_SCHOOL1, E_B_SCHOOL2, E_B_SCHOOL3, E_B_SCHOOL4, E_B_SCHOOL5, E_B_SCHOOL6, E_B_SCHOOL7, E_B_SCHOOL8, E_B_SCHOOL9, E_B_SCHOOL10, E_B_SCHOOL11, E_B_SCHOOL12, E_B_SCHOOL13,
        E_B_SCHOOL14, E_B_SCHOOL15, E_B_SCHOOL16, E_B_SCHOOL17, E_B_SCHOOL18, E_B_SCHOOL19, E_B_SCHOOL20, E_B_SCHOOL21, E_B_SCHOOL22, E_B_SCHOOL23, E_B_SCHOOL24, E_B_SCHOOL25,

        E_B_PRESENTS,
        E_B_PRESENTS0, E_B_PRESENTS1, E_B_PRESENTS2, E_B_PRESENTS3, E_B_PRESENTS4, E_B_PRESENTS5, E_B_PRESENTS6, E_B_PRESENTS7,

        E_B_TITLE_1,
        E_B_TITLE_1_0, E_B_TITLE_1_1, E_B_TITLE_1_2, E_B_TITLE_1_3, E_B_TITLE_1_4, E_B_TITLE_1_5, E_B_TITLE_1_6, E_B_TITLE_1_7, E_B_TITLE_1_8, E_B_TITLE_1_9, E_B_TITLE_1_10, E_B_TITLE_1_11, E_B_TITLE_1_12, E_B_TITLE_1_13,
        E_B_TITLE_1_14, E_B_TITLE_1_15, E_B_TITLE_1_16, E_B_TITLE_1_17, E_B_TITLE_1_18, E_B_TITLE_1_19,

        E_B_TITLE_2,
        E_B_TITLE_2_CURVE,
        E_B_TITLE_2_0, E_B_TITLE_2_1, E_B_TITLE_2_2, E_B_TITLE_2_3, E_B_TITLE_2_4, E_B_TITLE_2_5, E_B_TITLE_2_6, E_B_TITLE_2_7, E_B_TITLE_2_8,
        E_B_TITLE_2_9, E_B_TITLE_2_10, E_B_TITLE_2_11, E_B_TITLE_2_12, E_B_TITLE_2_13, E_B_TITLE_2_14, E_B_TITLE_2_15, E_B_TITLE_2_16,

        E_B_CAM_1,
        E_B_CAM_1_CURVE,


        E_B_COUNT,
};


// first scene
enum E_SCENE0{
        E_S0_ROOT = 0,
        // piano
        E_S0_PIANO_BODY,
        E_S0_PIANO_BENCH,
        E_S0_PIANO_STRINGS,
        // all keys
        E_S0_PIANO_C0, E_S0_PIANO_CC0, E_S0_PIANO_D0, E_S0_PIANO_DD0, E_S0_PIANO_E0, E_S0_PIANO_F0, E_S0_PIANO_FF0, E_S0_PIANO_G0, E_S0_PIANO_GG0, E_S0_PIANO_A0, E_S0_PIANO_AA0, E_S0_PIANO_B0,
        E_S0_PIANO_C1, E_S0_PIANO_CC1, E_S0_PIANO_D1, E_S0_PIANO_DD1, E_S0_PIANO_E1, E_S0_PIANO_F1, E_S0_PIANO_FF1, E_S0_PIANO_G1, E_S0_PIANO_GG1, E_S0_PIANO_A1, E_S0_PIANO_AA1, E_S0_PIANO_B1,
        E_S0_PIANO_C2, E_S0_PIANO_CC2, E_S0_PIANO_D2, E_S0_PIANO_DD2, E_S0_PIANO_E2, E_S0_PIANO_F2, E_S0_PIANO_FF2, E_S0_PIANO_G2, E_S0_PIANO_GG2, E_S0_PIANO_A2, E_S0_PIANO_AA2, E_S0_PIANO_B2,
        E_S0_PIANO_C3, E_S0_PIANO_CC3, E_S0_PIANO_D3, E_S0_PIANO_DD3, E_S0_PIANO_E3, E_S0_PIANO_F3, E_S0_PIANO_FF3, E_S0_PIANO_G3, E_S0_PIANO_GG3, E_S0_PIANO_A3, E_S0_PIANO_AA3, E_S0_PIANO_B3,
        E_S0_PIANO_C4, E_S0_PIANO_CC4, E_S0_PIANO_D4, E_S0_PIANO_DD4, E_S0_PIANO_E4, E_S0_PIANO_F4, E_S0_PIANO_FF4, E_S0_PIANO_G4, E_S0_PIANO_GG4, E_S0_PIANO_A4, E_S0_PIANO_AA4, E_S0_PIANO_B4,
        E_S0_PIANO_C5, E_S0_PIANO_CC5, E_S0_PIANO_D5, E_S0_PIANO_DD5, E_S0_PIANO_E5, E_S0_PIANO_F5, E_S0_PIANO_FF5, E_S0_PIANO_G5, E_S0_PIANO_GG5, E_S0_PIANO_A5, E_S0_PIANO_AA5, E_S0_PIANO_B5,
        E_S0_PIANO_C6, E_S0_PIANO_CC6, E_S0_PIANO_D6, E_S0_PIANO_DD6, E_S0_PIANO_E6, E_S0_PIANO_F6, E_S0_PIANO_FF6, E_S0_PIANO_G6, E_S0_PIANO_GG6, E_S0_PIANO_A6, E_S0_PIANO_AA6, E_S0_PIANO_B6,
        E_S0_PIANO_C7, E_S0_PIANO_CC7, E_S0_PIANO_D7, E_S0_PIANO_DD7, E_S0_PIANO_E7, E_S0_PIANO_F7, E_S0_PIANO_FF7, E_S0_PIANO_G7, E_S0_PIANO_GG7, E_S0_PIANO_A7, E_S0_PIANO_AA7, E_S0_PIANO_B7,
        E_S0_PIANO_C8, E_S0_PIANO_CC8, E_S0_PIANO_D8, E_S0_PIANO_DD8, E_S0_PIANO_E8, E_S0_PIANO_F8, E_S0_PIANO_FF8, E_S0_PIANO_G8, E_S0_PIANO_GG8, E_S0_PIANO_A8, E_S0_PIANO_AA8, E_S0_PIANO_B8,
        //puppet
        E_S0_PUPPET_UPPER_BODY,
        E_S0_PUPPET_LOWER_BODY,
        E_S0_PUPPET_LEFT_EYE,
        E_S0_PUPPET_LEFT_PUPIL,
        E_S0_PUPPET_LEFT_EYEBROW,
        E_S0_PUPPET_RIGHT_EYE,
        E_S0_PUPPET_RIGHT_PUPIL,
        E_S0_PUPPET_RIGHT_EYEBROW,
        E_S0_PUPPET_LEFT_ARM_PATH,
        E_S0_PUPPET_LEFT_ARM,
        E_S0_PUPPET_RIGHT_ARM,
        E_S0_PUPPET_LEFT_LEG,
        E_S0_PUPPET_RIGHT_LEG,
        E_S0_PUPPET_HEAD,
        E_S0_PUPPET_MOUTH_PATH,
        E_S0_PUPPET_MOUTH,
        E_S0_PUPPET_HAWK,
        // ground
        E_S0_GROUND,
        E_S0_CAM_1,
        E_S0_CAM_1_CURVE,
        // the end
        E_S0_THEEND,
        E_S0_THEEND0, E_S0_THEEND1, E_S0_THEEND2, E_S0_THEEND3, E_S0_THEEND4, E_S0_THEEND5,

        E_S0_COUNT,
};


// first scene
enum E_SCENE1{
        E_S1_ROOT = 0,
        // piano
        E_S1_PIANO_BODY,
        E_S1_PIANO_BENCH,
        E_S1_PIANO_STRINGS,
        // all keys
        E_S1_PIANO_C0, E_S1_PIANO_CC0, E_S1_PIANO_D0, E_S1_PIANO_DD0, E_S1_PIANO_E0, E_S1_PIANO_F0, E_S1_PIANO_FF0, E_S1_PIANO_G0, E_S1_PIANO_GG0, E_S1_PIANO_A0, E_S1_PIANO_AA0, E_S1_PIANO_B0,
        E_S1_PIANO_C1, E_S1_PIANO_CC1, E_S1_PIANO_D1, E_S1_PIANO_DD1, E_S1_PIANO_E1, E_S1_PIANO_F1, E_S1_PIANO_FF1, E_S1_PIANO_G1, E_S1_PIANO_GG1, E_S1_PIANO_A1, E_S1_PIANO_AA1, E_S1_PIANO_B1,
        E_S1_PIANO_C2, E_S1_PIANO_CC2, E_S1_PIANO_D2, E_S1_PIANO_DD2, E_S1_PIANO_E2, E_S1_PIANO_F2, E_S1_PIANO_FF2, E_S1_PIANO_G2, E_S1_PIANO_GG2, E_S1_PIANO_A2, E_S1_PIANO_AA2, E_S1_PIANO_B2,
        E_S1_PIANO_C3, E_S1_PIANO_CC3, E_S1_PIANO_D3, E_S1_PIANO_DD3, E_S1_PIANO_E3, E_S1_PIANO_F3, E_S1_PIANO_FF3, E_S1_PIANO_G3, E_S1_PIANO_GG3, E_S1_PIANO_A3, E_S1_PIANO_AA3, E_S1_PIANO_B3,
        E_S1_PIANO_C4, E_S1_PIANO_CC4, E_S1_PIANO_D4, E_S1_PIANO_DD4, E_S1_PIANO_E4, E_S1_PIANO_F4, E_S1_PIANO_FF4, E_S1_PIANO_G4, E_S1_PIANO_GG4, E_S1_PIANO_A4, E_S1_PIANO_AA4, E_S1_PIANO_B4,
        E_S1_PIANO_C5, E_S1_PIANO_CC5, E_S1_PIANO_D5, E_S1_PIANO_DD5, E_S1_PIANO_E5, E_S1_PIANO_F5, E_S1_PIANO_FF5, E_S1_PIANO_G5, E_S1_PIANO_GG5, E_S1_PIANO_A5, E_S1_PIANO_AA5, E_S1_PIANO_B5,
        E_S1_PIANO_C6, E_S1_PIANO_CC6, E_S1_PIANO_D6, E_S1_PIANO_DD6, E_S1_PIANO_E6, E_S1_PIANO_F6, E_S1_PIANO_FF6, E_S1_PIANO_G6, E_S1_PIANO_GG6, E_S1_PIANO_A6, E_S1_PIANO_AA6, E_S1_PIANO_B6,
        E_S1_PIANO_C7, E_S1_PIANO_CC7, E_S1_PIANO_D7, E_S1_PIANO_DD7, E_S1_PIANO_E7, E_S1_PIANO_F7, E_S1_PIANO_FF7, E_S1_PIANO_G7, E_S1_PIANO_GG7, E_S1_PIANO_A7, E_S1_PIANO_AA7, E_S1_PIANO_B7,
        E_S1_PIANO_C8, E_S1_PIANO_CC8, E_S1_PIANO_D8, E_S1_PIANO_DD8, E_S1_PIANO_E8, E_S1_PIANO_F8, E_S1_PIANO_FF8, E_S1_PIANO_G8, E_S1_PIANO_GG8, E_S1_PIANO_A8, E_S1_PIANO_AA8, E_S1_PIANO_B8,
        //puppet
        E_S1_PUPPET_UPPER_BODY,
        E_S1_PUPPET_LOWER_BODY,
        E_S1_PUPPET_LEFT_EYE,
        E_S1_PUPPET_LEFT_EYEBROW,
        E_S1_PUPPET_LEFT_PUPIL,
        E_S1_PUPPET_RIGHT_EYE,
        E_S1_PUPPET_RIGHT_EYEBROW,
        E_S1_PUPPET_RIGHT_PUPIL,
        E_S1_PUPPET_LEFT_ARM,
        E_S1_PUPPET_RIGHT_ARM,
        E_S1_PUPPET_LEFT_LEG,
        E_S1_PUPPET_RIGHT_LEG,
        E_S1_PUPPET_HEAD,
        E_S1_PUPPET_MOUTH_PATH,
        E_S1_PUPPET_MOUTH,
        E_S1_PUPPET_HAIR,
        E_S1_PUPPET_TIE,
        // ground
        E_S1_GROUND,
        E_S1_CAM_1,
        E_S1_CAM_1_CURVE,


        E_S1_COUNT,
};

void initScenes();

#endif