#ifndef MESH_H
#define MESH_H

#include <GL/gl.h>
#include <GL/glu.h>

#include "framework/meshmanager/meshmanager.h"

enum E_Mesh {
        E_MESH_PIANO_BODY = 0,
        E_MESH_PIANO_BENCH,
        E_MESH_PIANO_STRINGS,
        E_MESH_PIANO_WHITE_KEY,
        E_MESH_PIANO_BLACK_KEY,

        E_MESH_PUPPET_HEAD,
        E_MESH_PUPPET_HAIR,
        E_MESH_PUPPET_UPPER_BODY,
        E_MESH_PUPPET_LOWER_BODY,
        E_MESH_PUPPET_ARM,
        E_MESH_PUPPET_LEG,
        E_MESH_PUPPET_EYE,
        E_MESH_PUPPET_EYEBROW,
        E_MESH_PUPPET_MOUTH,
        E_MESH_PUPPET_HAWK,
        E_MESH_PUPPET_TIE,

        E_MESH_ALPHABET_A, E_MESH_ALPHABET_B, E_MESH_ALPHABET_C, E_MESH_ALPHABET_D, E_MESH_ALPHABET_E, E_MESH_ALPHABET_F, E_MESH_ALPHABET_G, E_MESH_ALPHABET_H, E_MESH_ALPHABET_I, E_MESH_ALPHABET_J,
        E_MESH_ALPHABET_K, E_MESH_ALPHABET_L, E_MESH_ALPHABET_M, E_MESH_ALPHABET_N, E_MESH_ALPHABET_O, E_MESH_ALPHABET_P, E_MESH_ALPHABET_R, E_MESH_ALPHABET_S, E_MESH_ALPHABET_T, E_MESH_ALPHABET_U,
        E_MESH_ALPHABET_V, E_MESH_ALPHABET_W, E_MESH_ALPHABET_Y, E_MESH_ALPHABET_Z, E_MESH_ALPHABET_CARKA, E_MESH_ALPHABET_HACEK,

        E_MESH_GROUND,

        E_MESH_COUNT,
};

void initMeshes();


#endif // MESH_H
